### ISSUE TITLE
fix spelling in example code

### ISSUE THREAD

**Issue by Caroline-Thies** [4xposed/rstidal#8]
Hi,
I was testing the example code and noticed that in the Cargo.toml, in the line
`tokio = { version = "0.2", feeatures = ["full"] }`
there is a spelling mistake, it should be "features" instead of "feeatures". Might also be a good opportunity to update the version number, just as an idea.

Great work on the crate!

**Comment by Caroline-Thies** [comment]
I opened a pull request for it :)

**Comment by 4xposed** [comment]
The PR has been merged, thanks!
